# ================== General ==================
Id: TeamViewer.TeamViewerHost
Publisher: TeamViewer AG
Name: TeamViewer Host
Author: TeamViewer AG
Description: TeamViewer is a comprehensive, remote access, remote control and remote support solution that works with almost every desktop and mobile platform, including Windows, macOS, Android, and iOS. TeamViewer lets you remote in to computers or mobile devices located anywhere in the world and use them as though you were there.
AppMoniker: teamviewerhost
Tags: remote desktop, remote access, remote control, web conferencing

# ================== License ==================
Homepage: https://www.teamviewer.com/
License: Free For Private, Non-Commercial Use.
LicenseUrl: https://www.teamviewer.com/en/eula/

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020) 
Version: 15.7.7

InstallerType: Nullsoft
Installers:
  - Arch: x86
    Url: https://download.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
    Sha256: abd5f8d2d35d266e9121de577234e11cc15de7ebf039e20a1e2068ba7af5dc4e
    Scope: machine
    
# ManifestVersion: 0.1.0
