Id: LutzRoeder.Netron
Version: 4.4.1
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.4.1/Netron-Setup-4.4.1.exe
    Sha256: C0AC2B5E0F55EACDD4481E2410A23E26CB50B30DAD93F7D567E1BDBD95238F89
