# ================== General ==================
Id: Ubisoft.Uplay
Publisher: Ubisoft
Name: Uplay
Author: Ubisoft
Description: Uplay service is a system that provides rewards and achievements for our players. This system also allows for games to use online content for statistics as well as the ability to share activities with friends.
AppMoniker: uplay
Tags: games, uplay, store, purchase

# ================== License ==================
Homepage: https://uplay.ubisoft.com
License: © Ubisoft Entertainment. All Rights Reserved.
LicenseUrl: https://legal.ubi.com/LegalInfoUbisoftEMEA

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020) 
Version: 112.0

InstallerType: Nullsoft
Installers:
  - Arch: Neutral
    Url: https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UplayInstaller.exe
    Sha256: ddd3cef75bb2b1f09b745da3d3e5e03d8a45518d79936150ff357659103e74ce
    Scope: machine
    
# ManifestVersion: 0.1.0
